### ISSUE TITLE
notify the group via the mailing list

### ISSUE THREAD

**Issue by npdoty** [patcg/patcg.github.io#2]
Notifications to the group are easily accomplished by messages to the mailing list to which all participants are automatically subscribed. The chairs have noted on the mailing list that they will send a message to the list for meeting and other announcements.

We could update the charter to indicate that notifications from the chairs will be sent to the mailing list, rather than through issues opened on a particular repo.

**Comment by npdoty** [comment]
Also, at least one of the internal links is broken; the anchor is `#notices` not `#notice`.

**Comment by AramZS** [comment]
Fixed that broken link, thanks!

**Comment by seanturner** [comment]
Now that we have the mailing list subscribed to get all issues/PRs entries (see [mail](https://lists.w3.org/Archives/Public/public-patcg/2022Jan/0002.html)), I think we can accomplish this pretty easily with some wording tweaks in [Annoucments](https://patcg.github.io/charter.html#notices) that explains this.
